export interface Appointment
{
    id: number,
    startTime: Date,
    endTime: Date,
    petName: string,
    petType: string,
    petBreed: string,
    veterinarian: string,
    customerName: string,
    streetAddress1: string,
    streetAddress2: string,
    city: string,
    stateName: string,
    stateAbbreviation: string,
    stateId: number,
    cellPhone: string,
    homePhone: string,
    workPhone: string,
    customerId: number,
    petBreedId: number,
    petTypeId: number,
    veterinarianId: number,
}